# Generated by Django 5.2.11 on 2026-02-10 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="body_placement",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="appointment",
            name="preferred_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.artist",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reference_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="appointments/designs/"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason for rejection (if rejected)"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="selected_style",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appointments.tattoostyle",
            ),
        ),
    ]
